service: monorepotest
# app and org for use with dashboard.serverless.com
app: monorepotest
org: phortonssf

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:stage, 'dev'}
  region: eu-west-1
